apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: joviandss-csi-driver-pvc-dynamic
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: joviandss-persisten-volume-sc
